### ISSUE TITLE
Logo Proposal :)

### ISSUE THREAD

**Issue by LuigiBaute** [VDelv/Ultra-Sound-Sensor-Project---H-S#1]
Greetings, @VDelv 

I wanted to collaborate with this project
by delivering a _free_ logo proposal,
If that's something you're interested in let me know!

I'm a Graphic Designer and an Open Source Enthusiast!
Cheers!
-Luigi.

**Comment by VDelv** [comment]
Hi @LuigiBaute

We are really interested in your collaboration.
That's really nice ! 

-Victor

**Comment by LuigiBaute** [comment]
Hello @VDelv I would like to ask a few things before proceeding to present the first proposal

What name would you like to be on the logo; Ultra Sound Sensor?

Do you have a current logo? or one in mind?

I'd like to know the _goal_ and the _message_ that should be intended on the logo...

Thanks!!!

**Comment by VDelv** [comment]
Hi, 

In fact the main goal of our project was to first design a car park (ultra sound sensor) and after improving it. We finally decide to design an autonomous car (https://www.youtube.com/watch?v=AbpuYF154vg).  

We would like "maze car" for the name of the logo. 

And the main message to intend on the logo is ultra sound sensor apply in car utilization. 

Thanks :)

**Comment by LuigiBaute** [comment]
Hello! @VDelv this is my first proposal, it can be in any color you want it, i'd like to hear any suggestion :+1: 
![propuesta logotipo ultra sound sensor](https://user-images.githubusercontent.com/36426974/40533038-6786a9d6-5fcf-11e8-90d4-444edf988621.png)

**Comment by nathancjr** [comment]
Hello,

I'm the colleague of @VDelv . The purple logo with a maze inside of the logo looks great ! It represents well the spirit of this project : a car equipped of three sensors (seen on the top, left and right) into the shape of a maze. The logo is not overloaded, maybe could you add an electronic circuit instead of the "M" inside the maze ? It would be perfect !

Nice job @LuigiBaute and thanks a lot !

Let's wait for @VDelv answer to have his opinion and determine which one he prefers.

Best regards,
Nathan

**Comment by VDelv** [comment]
Hi , 

I have nothing to say more than @nathancjr. Thank you a lot ! 
I really like the logo too 👍

**Comment by LuigiBaute** [comment]
Do you like it as it is now @VDelv Or I should update the ''M'' as @nathancjr suggested?
You're welcome, I'm really glad you like it.
if you like the purple one as it is I could submit a pull request (?)
by the way, where's the license of this project?, I couldn't find it.

**Comment by LuigiBaute** [comment]
![4 2](https://user-images.githubusercontent.com/36426974/40632104-5cd4ae5e-62b1-11e8-9207-1f0b3e775db7.png)
@VDelv  @nathancjr

**Comment by VDelv** [comment]
Yes, i agreed with Nathan suggestions. 

No problem for the pull request. 

We haven't putt any licence at the moment, do you need one ?

**Comment by LuigiBaute** [comment]
I contribute to open source project, therefore open source licenses too, Is this project gonna be it?

@VDelv 

I'll update (_in this issue_) the logo proposal when _I_ finish it :+1:

**Comment by LuigiBaute** [comment]
(_I'll close this pr since everything is already merged, if there's a logo update needed, It can be reopened._) 
I wasn't meant to close or make this comment in this repository

**Comment by nathancjr** [comment]
I uploaded the license file !

**Comment by LuigiBaute** [comment]
I apologyze @nathancjr I closed this issue by mistake, I was meant to close an issue on another repo.

on the good side, here is my logo update, I hope you like this!

![3](https://user-images.githubusercontent.com/36426974/40760523-2bc5f664-6465-11e8-917e-1f45ea64fdc1.png)

**Comment by LuigiBaute** [comment]
Hello @VDelv and @nathancjr ,
Did you see the logo proposal? 
Any suggestions?
I'm looking forward for your reply!

**Comment by LuigiBaute** [comment]
If you want me to make a new proposal just tell me I can come up with something new @nathancjr @VDelv  I'll be looking forward for your reply!

**Comment by nathancjr** [comment]
Sorry for the late answer, the updated purple logo fits perfectly our request (so the purple one at the bottom of the picture) ! Thanks 👍

So how shall we conclude this issue ?

**Comment by LuigiBaute** [comment]
I'll upload the .png to a folder on the repo (if wanted) or I'll just upload it on the readme.md, I'll also give you a google drive link (when ready) with its monochromatics versions and ready to use files like pdf, cdr, svg and .png @nathancjr

**Comment by LuigiBaute** [comment]
I've sended a pull request #2 and here's the [google drive](https://drive.google.com/open?id=1PkHsgesPgYx541IgBDo7l4lRBkfSjDOw) link with its monochromatics and ready to use files, such as pdf, svg, cdr and png.

@VDelv @nathancjr 

I'll close this issue now, 

Best Regards.
